
/* Drop Tables */

DROP TABLE IF EXISTS FAVORITE;
DROP TABLE IF EXISTS PROFILE;
DROP TABLE IF EXISTS GENDER;
DROP TABLE IF EXISTS OCCUPATION;
DROP TABLE IF EXISTS USERS;




/* Create Tables */

CREATE TABLE FAVORITE
(
	USER_ID int NOT NULL,
	FAVORITE_USER_ID int NOT NULL,
	PRIMARY KEY (USER_ID, FAVORITE_USER_ID)
) WITHOUT OIDS;


CREATE TABLE GENDER
(
	GENDER_ID serial NOT NULL,
	GENDER char(1) NOT NULL UNIQUE,
	PRIMARY KEY (GENDER_ID)
) WITHOUT OIDS;


CREATE TABLE OCCUPATION
(
	OCCUPATION_ID serial NOT NULL,
	OCCUPATION_NAME varchar(100) NOT NULL,
	PRIMARY KEY (OCCUPATION_ID),
	UNIQUE (OCCUPATION_ID)
) WITHOUT OIDS;


CREATE TABLE PROFILE
(
	USER_ID int NOT NULL,
	GENDER_ID int NOT NULL,
	NAME varchar(100) NOT NULL,
	BIRTHDAY date NOT NULL,
	HEIGHT int NOT NULL,
	OCCUPATION_ID int NOT NULL,
	INCOME int NOT NULL,
	TEXT varchar(255) NOT NULL,
	IMAGE bytea NOT NULL,
	PRIMARY KEY (USER_ID)
) WITHOUT OIDS;


CREATE TABLE USERS
(
	USER_ID serial NOT NULL,
	MAIL varchar(100) NOT NULL UNIQUE,
	PASS varchar(100) NOT NULL,
	PRIMARY KEY (USER_ID)
) WITHOUT OIDS;



/* Create Foreign Keys */

ALTER TABLE PROFILE
	ADD FOREIGN KEY (GENDER_ID)
	REFERENCES GENDER (GENDER_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE PROFILE
	ADD FOREIGN KEY (OCCUPATION_ID)
	REFERENCES OCCUPATION (OCCUPATION_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE FAVORITE
	ADD FOREIGN KEY (USER_ID)
	REFERENCES USERS (USER_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE PROFILE
	ADD FOREIGN KEY (USER_ID)
	REFERENCES USERS (USER_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;



